# -*- coding: utf-8 -*-
"""ML_Cheremsha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leLqBtfKVLrzM_2LnGPW0qDehJFu1l2V

# Импорты библиотек
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import joblib
import gdown
import json
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, roc_curve, classification_report
from sklearn.feature_selection import SelectKBest, f_classif
import xgboost as xgb

"""# Загрузка датасета"""

file_id='1G1fmKedJ5S64165Zs8IeU_uOZvj-OLhn'
url = f'https://drive.google.com/uc?id={file_id}'
output = 'dataset.csv'
gdown.download(url, output, quiet=False)

"""Прверяем, что датасет загрузился"""

import pandas as pd

df = pd.read_csv(output)
df.head()

"""# Первичный анализ данных

Размер датасета
"""

print(f'Размер датасета: {df.shape}, где \n{df.shape[0]} - количество строк \n{df.shape[1]} - количество столбцов')

"""Типы данных"""

print(f'Типы данных:\n{df.dtypes}')

"""Баланс классов"""

print(f'Баланс классов:\n{df['loan_status'].value_counts()}')

"""Доля одобренных ипотек"""

print(f'Доля одобренных ипотек: {df['loan_status'].mean():.2%}')

"""Количество пропусков"""

print(f'Количество пропусков:\n{df.isnull().sum()}')

"""# Очистка данных"""

df_clean = df.copy()

"""Обработка пропусков"""

numeric_cols = df_clean.select_dtypes(include=[np.number]).columns
for col in numeric_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].median(), inplace=True)

categorical_cols = df_clean.select_dtypes(include=['object']).columns
for col in categorical_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

print(f'Пропуски обработаны. Осталось: {df_clean.isnull().sum().sum()} пропусков')

"""Обработка выбросов"""

def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return df[(df[column] >= lower) & (df[column] <= upper)]

initial_len = len(df_clean)
outlier_cols = ['person_age', 'person_income', 'loan_amnt', 'credit_score']
for col in outlier_cols:
    df_clean = remove_outliers(df_clean, col)

print(f'Выбросы обработаны. Удалено: {initial_len - len(df_clean)} ({100*(initial_len - len(df_clean))/initial_len:.1f}%) выбросов')

"""# Визуализация данных"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# График 1: Credit Score vs Loan Status
good_credit = df_clean[df_clean['loan_status'] == 1]['credit_score']
bad_credit = df_clean[df_clean['loan_status'] == 0]['credit_score']

axes[0].hist(bad_credit, bins=30, alpha=0.5, label='Отказано', color='red', edgecolor='black', zorder=1)
axes[0].hist(good_credit, bins=30, alpha=0.8, label='Одобрено', color='#86c548', edgecolor='black', zorder=2)

axes[0].set_xlabel('Кредитный рейтинг (Credit Score)')
axes[0].set_ylabel('Частота')
axes[0].set_title('Распределение Credit Score по статусу ипотеки')

axes[0].axvline(good_credit.mean(), color='darkgreen', linestyle='dashed', linewidth=2.5,
                label=f'Средний (одобрено): {good_credit.mean():.0f}')
axes[0].axvline(bad_credit.mean(), color='darkred', linestyle='dashed', linewidth=2.5,
                label=f'Средний (отказ): {bad_credit.mean():.0f}')

axes[0].legend()

# График 2: Loan Percent Income vs Loan Status
good_income = df_clean[df_clean['loan_status'] == 1]['loan_percent_income']
bad_income = df_clean[df_clean['loan_status'] == 0]['loan_percent_income']

axes[1].hist(bad_income, bins=30, alpha=0.5, label='Отказано', color='red', edgecolor='black', zorder=1)
axes[1].hist(good_income, bins=30, alpha=0.8, label='Одобрено', color='#86c548', edgecolor='black', zorder=2)

axes[1].set_xlabel('Доля дохода на кредит (Loan Percent Income)')
axes[1].set_ylabel('Частота')
axes[1].set_title('Распределение Loan Percent Income по статусу ипотеки')

axes[1].legend()

plt.tight_layout()
# plt.show()
plt.savefig('eda_analysis.png', dpi=150)
plt.close()
print('\nГрафик сохранён: eda_analysis.png')

"""# Подготовка признаков (кодирование и масштабирование)"""

X = df_clean.drop('loan_status', axis=1)
y = df_clean['loan_status']

numeric_features = X.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = X.select_dtypes(include=['object']).columns.tolist()

print(f'\nЧисловые признаки ({len(numeric_features)}): {numeric_features}')
print(f'Категориальные признаки ({len(categorical_features)}): {categorical_features}')

numeric_transformer = Pipeline([('scaler', StandardScaler())])
categorical_transformer = Pipeline([('onehot', OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore'))])

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

X_processed = preprocessor.fit_transform(X)
feature_names = (numeric_features +
                 list(preprocessor.named_transformers_['cat']
                      .named_steps['onehot']
                      .get_feature_names_out(categorical_features)))

print(f'\nПосле One-Hot кодирования: {X_processed.shape[1]} признаков')

"""# Отбор признаков"""

selector = SelectKBest(score_func=f_classif, k=15)
X_selected = selector.fit_transform(X_processed, y)

selected_mask = selector.get_support()
selected_features = [feature_names[i] for i in range(len(feature_names)) if selected_mask[i]]

print(f'Отобрано {len(selected_features)} лучших признаков из {len(feature_names)}')
print(f'Топ-5 лучших признаков: {selected_features[:5]}')

"""# Обучение моделей"""

X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y, test_size=0.2, random_state=42, stratify=y
)

"""Модель XGBoost"""

xgb_model = xgb.XGBClassifier(
    n_estimators=150,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict_proba(X_test)[:, 1]
xgb_auc = roc_auc_score(y_test, xgb_pred)
print(f'XGBoost ROC-AUC: {xgb_auc:.4f}')

# Кросс-валидация
xgb_cv = cross_val_score(xgb_model, X_train, y_train, cv=5, scoring='roc_auc')

print(f'5-fold кросс-валидация:')
print(f'  XGBoost: {xgb_cv.mean():.4f} (+/- {xgb_cv.std():.4f})')

"""Модель Random Forest"""

rf_model = RandomForestClassifier(
    n_estimators=150,
    max_depth=12,
    min_samples_split=5,
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict_proba(X_test)[:, 1]
rf_auc = roc_auc_score(y_test, rf_pred)
print(f'Random Forest ROC-AUC: {rf_auc:.4f}')

# Кросс-валидация
rf_cv = cross_val_score(rf_model, X_train, y_train, cv=5, scoring='roc_auc')

print(f'5-fold кросс-валидация:')
print(f'  Random Forest: {rf_cv.mean():.4f} (+/- {rf_cv.std():.4f})')

"""# Выбор лучшей модели"""

if xgb_auc > rf_auc:
    best_model = xgb_model
    best_model_name = 'XGBoost'
    best_auc = xgb_auc
    print(f'Лучшая модель: XGBoost (ROC-AUC = {best_auc:.4f})')
else:
    best_model = rf_model
    best_model_name = 'Random Forest'
    best_auc = rf_auc
    print(f'Лучшая модель: Random Forest (ROC-AUC = {best_auc:.4f})')

"""Итоговая метрика"""

print(f'Итоговый ROC-AUC на тестовой выборке: {best_auc:.4f}')

"""Вывод по метрикам"""

y_pred_class = best_model.predict(X_test)
print(f'\n{classification_report(y_test, y_pred_class, target_names=['Отказ', 'Одобрение'])}')

"""ROC-кривая для лучшей модели"""

plt.figure(figsize=(10, 10))
fpr, tpr, _ = roc_curve(y_test, best_model.predict_proba(X_test)[:, 1])
plt.plot(fpr, tpr, label=f'{best_model_name} (AUC = {best_auc:.4f})', linewidth=2)
plt.plot([0, 1], [0, 1], 'k--', label='Случайная модель (AUC = 0.5)')
plt.grid(True, alpha=0.3, linestyle='--')
plt.xlabel('False Positive Rate (FPR) - доля ошибочно одобренных среди реальных отказов')
plt.ylabel('True Positive Rate (TPR) - доля правильно одобренных среди реальных одобрений')
plt.title(f'ROC-кривая лучшей модели: {best_model_name}')
plt.legend()
# plt.show()
plt.grid(alpha=0.3)
plt.savefig('best_model_roc.png', dpi=150)
plt.close()
print('\nГрафик сохранен: best_model_roc.png')

"""# Сохранение пайплайна и признаков

Пайплайн
"""

full_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('selector', selector),
    ('classifier', best_model)
])

full_pipeline.fit(X, y)

joblib.dump(full_pipeline, 'model.pkl')
print('model.pkl сохранен (полный пайплайн)')

"""Признаки"""

features_info = {
    'selected_features': selected_features,
    'all_original_features': X.columns.tolist(),
    'numeric_features': numeric_features,
    'categorical_features': categorical_features,
    'best_model': best_model_name,
    'roc_auc_score': float(best_auc),
    'n_selected_features': len(selected_features),
    'model_parameters': str(best_model.get_params())
}

with open('features.json', 'w', encoding='utf-8') as f:
    json.dump(features_info, f, indent=2, ensure_ascii=False)
print('features.json сохранен')